name: "Setup"
description: "Setup Node.js, pnpm, caches, and install dependencies"

inputs:
  node-version:
    description: "Node.js version"
    required: false
    default: "24"
  cache-nextjs:
    description: "Enable Next.js build cache"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Cache Turbo
      uses: actions/cache@v5
      with:
        path: .turbo
        key: turbo-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}-${{ github.sha }}
        restore-keys: |
          turbo-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}-
          turbo-${{ runner.os }}-

    - name: Cache Next.js
      if: inputs.cache-nextjs == 'true'
      uses: actions/cache@v5
      with:
        path: apps/dashboard/.next/cache
        key: nextjs-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}-${{ hashFiles('apps/dashboard/**/*.ts', 'apps/dashboard/**/*.tsx') }}
        restore-keys: |
          nextjs-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}-
          nextjs-${{ runner.os }}-

    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: "pnpm"

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
